name: Infrastructure-Deployment-$(Build.SourceBranchName)-$(Date:yyyyMMdd)

variables:
  TFSTATE_SA: iacbootslab
  TFSTATE_CONTAINER: tfstate-demo
  TFSTATE_KEY: terraform.tfstate
  TFSTATE_RG: demo
  SVC_CONNECTION: eng-lab-automation

trigger:
- duplicate_tf_build

pool: linux-agent-pool

stages: 
- stage: Terraform_build
  jobs:
  - job: Build
    steps:
    - task: TerraformCLI@2
      displayName: 'Initialization'
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        commandOptions: '-upgrade'
        backendType: 'azurerm'
        backendServiceArm: 'eng-lab-automation'
        backendAzureRmResourceGroupName: '$(TFSTATE_RG)'
        backendAzureRmStorageAccountName: '$(TFSTATE_SA)'
        backendAzureRmContainerName: '$(TFSTATE_CONTAINER)'
        backendAzureRmKey: '$(TFSTATE_KEY)'
        allowTelemetryCollection: true   

    - task: TerraformCLI@2
      displayName: 'Execute Plan'
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        environmentServiceName: $(SVC_CONNECTION)
        allowTelemetryCollection: true
        publishPlanResults: 'output.tfplan'
        commandOptions: '-lock=false -input=false -out=$(System.DefaultWorkingDirectory)/dev/output.tfplan'

    # Publish the output.tfplan file as an artifact
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Terraform Plan as Artifact'
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/dev/output.tfplan'
        artifact: 'tfplan'

- stage: Terraform_Deploy
  dependsOn: Terraform_build
  jobs:
  - job: Deploy
    steps:
    - download: current
      artifact: tfplan

    - task: TerraformCLI@2
      displayName: 'Deploy'
      inputs:
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/dev'
        environmentServiceName: $(SVC_CONNECTION)
        commandOptions: '-input=false $(System.DefaultWorkingDirectory)/tfplan/output.tfplan'
        allowTelemetryCollection: true
